#!/usr/bin/perl -w
#
#eg cat logfile |rcg "fatal" "BOLD . YELLOW . ON_WHITE"
#   cat logfile |rcg "WARN" "RED" "INFO" "YELLOW"
#
# From the Linux Server Hacks O'Reilly book

use strict;
use Term::ANSIColor qw(:constants);

my %target = ( );

while (my $arg = shift) {

	my $clr = shift;

    if (($arg =~ /^-/) | !$clr) {
		print "Usage: rcg [regex] [color] [regex] [color] ...\n";
		exit(2);
    }

    #
    # Ugly, lazy, pathetic hack here.
    #
    $target{$arg} = eval($clr);
}

my $rst = RESET;

while(<>) {
	foreach my $x (keys(%target)) {
		s/($x)/$target{$x}$1$rst/g;
	}
	print
}
